### PR TITLE
Temporary fix for scikit-build on macs

### LINKED ISSUE #212: pip install doesn't work for macosx (arm64)
It seems PR #210 results in failing `pip install` even without `-e`.

The error shows `wheel/macosx_libfile.py` complains. `wheel` package is invoked by skbuild. It seems this is difficult to fix (for me), but critical. Until this issue will be fixed someday, I think it is better a little bit to step back.

How about making static link library using cmake, then link it in `setup.py` without relying on skbuild?

Ping @LecrisUT.

### PR DESCRIPTION
**Pull request by LecrisUT**
Fixes #212

### CODE REVIEW

**Comment by LecrisUT** [comment]
@atztogo Can you confirm this works? I will upstream this fix to scikit-build later if it does

**Comment by atztogo** [comment]
@LecrisUT, thanks for your quick work. Almost. The following change at least made it work.
```diff
% git diff setup.py
diff --git a/python/setup.py b/python/setup.py
index f5d40e1..42a79eb 100644
--- a/python/setup.py
+++ b/python/setup.py
@@ -5,9 +5,9 @@ from skbuild import setup
 # TODO: Temporary fix for #212
 #  Remove and update dependency when scikit-build/scikit-build#717 is resolved
 import platform
-if platform.version() == 'Darwin':
+if platform.system() == 'Darwin':
     mac_version, _, mac_arch = platform.mac_ver()
-    mac_version = f"{mac_version}-{mac_arch}"
+    mac_version = f"{mac_version}"
 else:
     mac_version = None

@@ -75,7 +75,7 @@ setup(
     tests_require=[
         "pyyaml",
     ],
-    cmake_args=['-DWITH_Python=ON', '-DWITH_TESTS=OFF', '-DUSE_OMP=OFF', '-DBUNDLE_Python_SharedLib=ON'],
+    cmake_args=cmake_args,
     cmake_source_dir="..",
     extras_require=extras_require,
 )
```

**Comment by LecrisUT** [comment]
Oh god. I've derped that commit bad. Sorry about that. I am surprised why we don't need to set up [`CMAKE_OSX_ARCHITECTURES`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) as well.

**Comment by atztogo** [comment]
Merged. Thanks @LecrisUT. Your PR worked on my macOS.

**Pull request merged**
