### PR TITLE
Redirect GitHub pages to Read the Docs

### PR DESCRIPTION
**Pull request by lan496**
Related: https://github.com/spglib/spglib/pull/253

- Redirect the root page as [https://spglib.github.io/spglib](https://spglib.github.io/spglib/index.html) → [https://spglib.readthedocs.io/en/latest/](https://spglib.readthedocs.io/en/latest/)
- Redirect subpages as [https://spglib.github.io/spglib/api.html](https://spglib.github.io/spglib/api.html) → [https://spglib.readthedocs.io/en/latest/api.html](https://spglib.readthedocs.io/en/latest/api.html)

### CODE REVIEW

**Comment by lan496** [comment]
Note: I've checked this approach in my project, https://github.com/lan496/hsnf/tree/gh-pages.
- https://lan496.github.io/hsnf → https://hsnf.readthedocs.io/en/latest/
- https://lan496.github.io/hsnf/definition.html → https://hsnf.readthedocs.io/en/latest/definition.html

**Comment by LecrisUT** [comment]
Confirmed it works on root as well, i.e. https://lan496.github.io.

Lgtm

**Review by atztogo — APPROVED** [review]
Good!

**Comment by LecrisUT** [comment]
Lool, RTD reported this as a successful build :)) https://spglib--263.org.readthedocs.build/en/263/

**Pull request merged**
