### PR TITLE
Update documentation link

### LINKED ISSUE #252: Deprecate github.io documentation
So far the readthedocs documentation works well, but there are a few situation to test
- [x] Pushing tags. The recent tag `v2.1.0-rc1` did not create a new documentation. Not sure if it is a webhook issue or rtd configuration issue
- [ ] Missing previous documentations. We can add a branch and a few patch versions to push the documentation, but is it worth it? Which version is the documentation well maintained to push?

To migrate we have to:
- [ ] Change the reference in github 
- [ ] Deactivate the github action related to it
- [ ] Change the reference in the source code
- [ ] Change the reference in `PyPI` and `conda`

### PR DESCRIPTION
**Pull request by LecrisUT**
- [ ] Update documentation link on Conda [conda-forge/spglib-feedstock#82](https://github.com/conda-forge/spglib-feedstock/pull/82)
- [ ] Update documentation link on PyPI @lan496 
- [ ] Redirect https://spglib.gihub.io and https://spglib.gihub.io/spglib to https://spglib.readthedocs.io

The other note I had was about what do we do with previous versions? Do we want to recreate them, or should we just consider this version moving on to be maintained?

Closes: #252

### CODE REVIEW

**Review by lan496 — COMMENTED** [review]
@LecrisUT LGTM so far. How to redirect github.io to readthdocs.io? One way will be just to put index.html with a meta refresh tag.
https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

@atztogo I do not have permission to update the link on PyPI? Can you update it to https://spglib.readthedocs.io/ ?

**Comment by atztogo** [comment]
Maybe `pyproject.toml` to change URL link on PyPI?

**Comment by LecrisUT** [comment]
Ok, we should see it in test.pypi on the next rc then. I'll let you handle the github page redirect. Just make sure you do it for both the base and the spglub subfolder

**Review by lan496 — APPROVED** [review]
Ok. I'll work the redirection on `gh-pages` branch after this PR is merged.

**Pull request merged**
