### PR TITLE
Release v2.3.1

### LINKED ISSUE #424: Release v2.3.1
A few bugfixes:
- #423 
- #421 (fixup: #427) 
- #426

Incidentally, we need #422 to fix the CI as well.

This is all I have on my side that would merit a bugfix release. Any thoughts?

### PR DESCRIPTION
**Pull request by lan496**
Closes https://github.com/spglib/spglib/issues/424

After this PR is merged, I'll put `v2.3.1-rc1` tag to the commit first. Then `v2.3.1` tag.

### CODE REVIEW

**Review by atztogo — APPROVED** [review]
Thanks @lan496!

**Review by LecrisUT — APPROVED** [review]
Don't put multiple tags on the same commit, or at least delete the old tag and wait a while before tagging a new one.

There was an issue where the git archive sha changed and my suspicion is that that's what caused it. (The `.git_archival.txt` file changes on every commit and tag)

**Comment by lan496** [comment]
I see. Then, I just put `v2.3.1` tag

**Comment by lan496** [comment]
```
gco -
git pull upstream develop
git tag v2.3.1
git push upstream v2.3.1
```

**Comment by lan496** [comment]
Uploaded to PyPI
https://pypi.org/project/spglib/2.3.1/

**Comment by lan496** [comment]
GitHub release note https://github.com/spglib/spglib/releases/tag/v2.3.1

**Pull request merged**
