### PR TITLE
Cmake refactoring

### PR DESCRIPTION
**Pull request by LecrisUT**
Bare with me on this one, it is a beast of a refactoring:
- 51e15ad0383090c74d71a963fe4b41b03e636dfe: Renamed cmake options to be more consistent with good practices suggested by Craig Scott (prominent cmake maintainer). This is from a [discussion on libxc](https://gitlab.com/libxc/libxc/-/merge_requests/604#note_1269097307).
- e19b59c814e8a051686b9019383286273c1255d9, 2538feb0fcca85162d18c18076c12dd90be9f22f: Similar to the previous one, some good practices
- 8d41b3145fdbb4fbb041e8ab2df5c388a9921add: Random improvement if you want to run `cmake --install --component Spglib_Development` to install only specific components. Might be useful downstream if they want to install only specific files from this
- b4128d30697a34c53e84e3fe1eafc21849b56434: Add an alias library `libsymspg-omp` that is guaranteed to be built with OpenMP. The main library is still built with OpenMP, but subsequent runs might overwrite it. This makes more sense with the next changes
- 4b520c19f90629470ff50da7365dd1a46e9d9a60, f9a1548c9124f87d1003c086bd57b4435ee78ece: Implement components. More bellow
- 3c715888abded8e2ff0f3aa7b47128b916446c74: Disabled install completely when project is imported via `ExternalProject`

We can use components like:
```cmake
find_package(Spglib COMPONENTS omp static
    OPTIONAL_COMPONENTS fortran)
```
Which will test that spglib is built with `omp` and as a `static` library, but also include `fortran` if available. If not passed any components, it will try to load all components. Normally components should only be optional additional libraries, but here we have 2 special cases:
- `shared` and `static`: These components will switch what kind of libraries to include in the project, i.e. to link as a shared or static library. These are optional and if not passed, it will try to figure out from `SPGLIB_SHARED_LIBS` (required to be as it is defined) or `BUILD_SHARED_LIBS` if defined (allows to fallback to what's available)
- `omp`: This includes the `libsyspg-omp` library. This is effectively a copy of `libsymspg` that is guaranteed to be built via OpenMP. Normally we should not be including the build options as components like that, but often times you can see exceptions for MPI and OpenMP types (e.g. in package distributions).

I have disabled completely install steps when spglib is imported via `ExternalProject`. This could otherwise lead to overwriting the system installed version. I couldn't find a clean way to allow installation safely, so I've left a note to contact us about how it should be done.

Luckily we have not yet pushed a `2.1` release with the options changes, so there is little affecting downstream.

### CODE REVIEW

**Comment by lan496** [comment]
@LecrisUT Thanks for the refactoring and improvements of documents!
Just curious, how the target `Spglib_symspg` defined in `CMakeLists.txt` are resolved as `Spglib::symspg` as shown in `example/CMakeLists.txt` (not `Spglib::Spglib_symspg`)?
Is it a CMake functionality (if so, where is it officially documented), or resolved in spglib's side?

**Comment by LecrisUT** [comment]
This I got from the discussion in Libxc. Specifically it is controlled by [`EXPORT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/EXPORT_NAME.html) [here](https://github.com/spglib/spglib/blob/7add6372a0d1cb0e3bab6750cec0a17d0de9f060/CMakeLists.txt#L62). The complete documentation of all of the cmake (target) properties is [here](https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#properties-on-targets) (`man cmake-properties`)

**Review by lan496 — APPROVED** [review]

**Comment by LecrisUT** [comment]
Rebased it onto `develop` and cleaned up the documentation, let me know if you find it cleaner now.

A few things though:
- @atztogo Can you make the `example_c`  and/or `example_f08` more minimal so that it has more realistic example? Also have a very simple example in the main README of what spglib can do.
- @atztogo I have removed your `tetrahedron.c` example because it couldn't be compiled without `tetrahedron.h`, is it ok, or can you otherwise add all the necessary files here?
- Is the mailing list in sourceforge (https://sourceforge.net/p/spglib/mailman/) still active? Should we get rid of it and use Github and maybe gitter/matrix/irc for more live channels?

**Comment by atztogo** [comment]
@LecrisUT, @lan496, I have a minor question. I just recently know cmake option of `-B`. Currently the spglib documentation it is written like below. 
```
$ mkdir build
$ cd build
$ cmake .. ${CMAKE_OPTIONS}
$ cmake --build .
$ cmake --install .
```
But it can be also
```
$ cmake -B build ${CMAKE_OPTIONS} .
$ cmake --build build
$ cmake --install build
```
Which do you prefer?

**Comment by atztogo** [comment]
> * @atztogo Can you make the `example_c`  and/or `example_f08` more minimal so that it has more realistic example? Also have a very simple example in the main README of what spglib can do.

I agree. It was also used as tests. We have (C) and are preparing  (Fortran) tests, so I agree. Can it be written in an issue?

**Comment by atztogo** [comment]
> * @atztogo I have removed your `tetrahedron.c` example because it couldn't be compiled without `tetrahedron.h`, is it ok, or can you otherwise add all the necessary files here?

OK! Thanks.

**Comment by atztogo** [comment]
> * Is the mailing list in sourceforge (https://sourceforge.net/p/spglib/mailman/) still active? Should we get rid of it and use Github and maybe gitter/matrix/irc for more live channels?

Sourceforge mailing list is not at all very active. We can use github instead. I have no idea about gitter/matrix/irc. Only github is not enough?

**Review by atztogo — APPROVED** [review]
Great!

**Comment by lan496** [comment]
> Which do you prefer?

@atztogo I like the latter because it needs fewer commands, although [a bit newer CMake >= 3.13 is required](https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html).

**Comment by LecrisUT** [comment]
> @LecrisUT, @lan496, I have a minor question. I just recently know cmake option of `-B`. Currently the spglib documentation it is written like below.
> 
> Which do you prefer?

Oh yeah, I completely forget about `-B`. I'm also ok with rewriting it to that.

>  I have no idea about gitter/matrix/irc. Only github is not enough?

Sure, only github is fine. The others are like slack, but open sourced. All those 3 are interoperable. I'm always reachable on matrix if someone wants to discuss something there.

**Pull request merged**
