### PR TITLE
Various cmake cleanups

### PR DESCRIPTION
**Pull request by LecrisUT**
Some cmake cleanups and improvements
- Removed openmp specific target (keep things simple for now)
- Making top cmake file more readable
- Make it more compatible with FetchContent (propagating `Spglib_VERSION` and other such variables)
- Added `SPGLIB_INSTALL`. More inline with other projects standard

### CODE REVIEW

**Comment by LecrisUT** [comment]
Seems like address sanitizer is detecting some errors in `test_magnetic_symmetry.test_spgms_get_magnetic_dataset_high_mag_symprec`

Weird. Why is it only triggered here? I am able to replicate this issue locally

**Comment by LecrisUT** [comment]
@lan496 about 054ceca2e6d7df1b85c1025c3f36767b20333d5a. Are sanitizers needed in the c++ part of gtests? I have disabled it because it was reported as:
```
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
```

**Comment by lan496** [comment]
@LecrisUT I think it is not necessary. Actually, I remember `test_magnetic_symmetry.test_spgms_get_magnetic_dataset_high_mag_symprec` sometimes causes such a strange warning on the address sanitizer.

**Review by lan496 — APPROVED** [review]
Thanks, LGTM!

**Comment by LecrisUT** [comment]
Lets hold off to check the CI from #285 first

**Pull request merged**
