### PR TITLE
Update references to spglib paper

### PR DESCRIPTION
**Pull request by atztogo**
Updated references to the spglib paper, now published in the Science and Technology of Advanced Materials (STAM): Method journal.

### CODE REVIEW

**Comment by LecrisUT** [comment]
I think I know why the CI is failing and I'm internally happy about this (they are pushing people to actually modernize the CMake), although people might not catch on to this until it's in Ubuntu LTS. I'll make a PR to unblock the CIs.

Edit: ah I was excited for nothing, this is only because of our CI setup
https://github.com/spglib/spglib/blob/0c1fca6c904a2c3a867f1c7c1128546392e5e172/cmake/CMakePresets-CI.json#L36-L38

Anyway this is resolved in https://github.com/spglib/spglib/pull/535

**Comment by atztogo** [comment]
What is sphinx-linkcheck?
```
(           index: line   32) broken    https://onlinelibrary.wiley.com/iucr/doi/10.1107/S2053273323005016 - 403 Client Error: Forbidden for url: https://onlinelibrary.wiley.com/iucr/doi/10.1107/S2053273323005016
(       interface: line   10) ok        https://github.com/spglib/spglib/tree/develop/fortran/spglib_f08.F90
(           index: line   58) ok        https://spglib.readthedocs.io/
(           index: line   28) broken    https://www.tandfonline.com/doi/full/10.1080/27660400.2024.2384822 - 403 Client Error: Forbidden for url: https://www.tandfonline.com/doi/full/10.1080/27660400.2024.2384822
```

**Comment by atztogo** [comment]
Still this fails.
```
(           index: line   28) broken    https://doi.org/10.1080/27660400.2024.2384822 - 403 Client Error: Forbidden for url: https://www.tandfonline.com/doi/full/10.1080/27660400.2024.2384822
```

**Comment by LecrisUT** [comment]
sphinx-linkcheck checks that a URL is accessible without being redirected elsewhere. It is setup such that the doi links are allowed to be redirected and those should be preferred. Why it gives a 403, I would need to try it out locally, but I have a clue: https://github.com/sphinx-doc/sphinx/issues/10343#issuecomment-1097430133

Adding it to `linkcheck_ignore` is good for now though

**Review by lan496 — APPROVED** [review]

**Pull request merged**
