### PR TITLE
Change installation location of spglib_f08.mod

### PR DESCRIPTION
**Pull request by atztogo**
I think `.mod` file of fortran should be put in `include` directory when installing.

### CODE REVIEW

**Comment by LecrisUT** [comment]
Seems reasonable since it is used with a `-I` flag.

Also need to fix in:
https://github.com/spglib/spglib/blob/aee574d8f7f385415fbd2cda0a44dd13322d920d/fortran/spglib_f08.pc.in#L8
and
https://github.com/spglib/spglib/blob/aee574d8f7f385415fbd2cda0a44dd13322d920d/fortran/CMakeLists.txt#L17

**Comment by LecrisUT** [comment]
Also, we don't have tests for
- fortran function calls
- package install imports.

First one should be possible in the `ctest`. Not sure about a standard to do the latter.

**Comment by atztogo** [comment]
Thanks @LecrisUT!

> Also need to fix in:

I included your fixes although I don't understand them :).

> Also, we don't have tests for

I am looking at how to write fortran tests using ctest. I put it in an issue #225.

> * package install imports.

I have really no idea on this...

**Comment by atztogo** [comment]
I will close this PR because what was aimed was achieved by #226.

**Pull request closed without merging**
