### PR TITLE
Add the name of National Institute for Materials Science

### PR DESCRIPTION
**Pull request by atztogo**
I am asked to write my institute to include in the copyright. @lan496, @LecrisUT, do you think I can do it?

### CODE REVIEW

**Comment by LecrisUT** [comment]
I am ok with it

**Comment by lan496** [comment]
Of course, I'm also OK with it. But I feel your previous affiliation is also eligible to be denoted.

**Comment by LecrisUT** [comment]
There is also the `pyproject.toml` file

**Comment by atztogo** [comment]
> There is also the `pyproject.toml` file

Thanks, but I don't see where I can put it...

> Of course, I'm also OK with it. But I feel your previous affiliation is also eligible to be denoted.

Yes. It will be done on demand. Those people don't see PR etc, but watch the web page. I also updated `doc/index.md` if both of you don't mind.

I have been lazy for this kind of stuff. It would also be nice if there is any chance to let contributors happy by making their efforts clearer (to, maybe, non-developers, etc). But I don't know how it can be done in a fair way. Now we have multiple big contributors. So the top page should be reconsidered. I have kept my name exposed there not to let other people too much obliged for the maintenance or user support etc.

**Comment by LecrisUT** [comment]
https://github.com/spglib/spglib/blob/8da92797544572840ef0229741fa04f809ce5fa5/pyproject.toml#L18-L20

> I have been lazy for this kind of stuff. It would also be nice if there is any chance to let contributors happy by making their efforts clearer (to, maybe, non-developers, etc). But I don't know how it can be done in a fair way. Now we have multiple big contributors. So the top page should be reconsidered. I have kept my name exposed there not to let other people too much obliged for the maintenance or user support etc.

Let's open an issue to discuss this. I don't know the appropriate approach, but maybe someone at NIMS can help us discuss how to fairly attribute contributors.

**Comment by atztogo** [comment]
I close this PR. I reconsider @lan496's comment, and at this moment, COPYING file is not changed. I raised an issue #443 following @LecrisUT's suggestion.

**Pull request closed without merging**
