### PR TITLE
chore: Bump cmake 3.25

### PR DESCRIPTION
**Pull request by LecrisUT**
Ubuntu 24.04 is out with CMake 3.28
RHEL9  bumped the CMake  3.26

### CODE REVIEW

**Comment by LecrisUT** [comment]
Well, this one is ready to be merged, since the current LTS distros have CMake >= 3.25. Waited a grace period after `2.5` was released to catch any bug fixes and so far there is only #519 and #517. After those 2 are merged, this can be merged, and if we catch more bugs that need to be backported, we can just cherry-pick those later.

**Comment by lan496** [comment]
Ping me after these two PRs are merged just to be sure.

**Review by lan496 — APPROVED** [review]
LGTM

@atztogo Do you have any concerns about bumping up CMake's version?

**Comment by atztogo** [comment]
> @atztogo Do you have any concerns about bumping up CMake's version?

Honestly, I have no idea and no objection. Please go ahead.

**Review by atztogo — APPROVED** [review]

**Comment by LecrisUT** [comment]
`pip install` wise it is completely transparent, because skbuild-core (at least as of 0.10) will read the minimum CMake from `CMakeLists.txt` and if it's not satisfied, it will effectively add `cmake` to the `build-system.requires` and thus use the version from PyPI. If users only want the C library, and they are on outdated distros, they should similarly `pip install cmake`. The only audience that should be affected are packagers, hence the delay up to now.

**Pull request merged**
