### PR TITLE
Release v2.1.0

### LINKED ISSUE #239: Version 2.1
Should we push some `2.1-rc` releases with the current changes? Mostly we will need to finish checking if everything is ok moving forward.
- [ ] Are the cmake options all ok in the new form?
- [ ] Naming of the targets and other conventions are ok?

Otherwise there are a few things we might want to finish before publishing `2.1.0`
- [x] #236 
- [x] #240 

Let me know of any other things to add to the list

### PR DESCRIPTION
**Pull request by lan496**
Close: https://github.com/spglib/spglib/issues/239

After this PR is merged, I'll put `v2.1.0` tag to the commit.

### CODE REVIEW

**Comment by lan496** [comment]
Note: I generated the list of PRs by `gh` command though this task will be automated in future.
```
gh pr list --state merged --limit 99 --json url,title,number | jq -r '.[] | "[[#\(.number)]](\(.url)) - \(.title)"' 
```

**Comment by lan496** [comment]
What happened on rpm-build CIs?

**Review by atztogo — APPROVED** [review]
@lan496, thanks for your work. Probably categorising commits requires some effort.

**Comment by LecrisUT** [comment]
That is weird, `aarch64` are failing due to the build system infrastructure, I'll ask around what is going on.

Last build was successful so you can go ahed with this one. (On the fedora downstream side, there is a different infrastructure)

**Review by LecrisUT — APPROVED** [review]

**Comment by lan496** [comment]
I've pushed `v2.1.0` tag to upstream.
```shell
git checkout develop
git pull upstream develop
git tag v2.1.0
git push upstream v2.1.0
```

**Comment by lan496** [comment]
https://github.com/spglib/spglib/actions/runs/6135805202/job/16650183543
Configuration for Trusted Publisher seems to be incorrect.

**Comment by lan496** [comment]
Rerun the failed pypi publish after fixing Trusted Publisher Management in PyPI and TestPyPI (fix to rename `release.yml` to `release.yaml`).

**Comment by lan496** [comment]
spglib v2.1.0 is published in PyPI 🎉
https://pypi.org/project/spglib/

**Comment by lan496** [comment]
GitHub's release is nicely generated: https://github.com/spglib/spglib/releases/tag/untagged-6db672e52eb611e6598b

**Comment by LecrisUT** [comment]
@lan496 please convert draft releases to proper releases after you reviewed it

**Comment by lan496** [comment]
@LecrisUT Thanks. I've converted. I didn't know that a draft is not seen by the public.

**Pull request merged**
