### PR TITLE
func(Layer group): add layer group support

### PR DESCRIPTION
**Pull request by site-g**
Hello, I tried making `det_determine_all` to support detection of layer group. I have tested some of the materials in [C2DB](https://cmrdb.fysik.dtu.dk/c2db/) and get the right results (wrote in example.c). But I'm not so sure about the modification of the interfaces. Should I write some layer group countparts or just add new arguments in the existing functions? I have tried to avoid modifying non-static functions as much as possible. The most significant change might be the adding of `int aperiodic_axis` in `Cell`. Will this break the compatibility?

Are you interested in collaborating to implement this feature, or would you mind give me some suggestions on naming convention, coding style and compatibility? Thank you.

Summary of changes:
- Add aperiodic_axis in structure Cell to indicate aperiodic direction.

- Negative hall number represents layer group.

- Add layer group sym and sitesym database.

- Mod 1 along aperiodic direction is removed.

- Adjusts behaviour of Delaunay and Niggli reduction.

- Aperiodic axis of conventional cell transforms to c.
- Aperiodic direction of primitive cell does not change.

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks! I am not familiar with layer group. Could you send me an e-mail (see the address http://spglib.github.io/spglib/) to arrange a virtual meeting if you don't mind?

**Comment by site-g** [comment]
The definition for layer group is simple, it is three-dimensional groups with two-dimensional translations, which means one axis  of the cell is non-periodic. For example, if **_c_** is non-periodic, there shoud be no screw axis or glide plane outside **_ab_** plane or 3, 4, 6 order rotation in plane. It is a subgroup of spacegroup.

**Comment by site-g** [comment]
I have sent an e-mail. Did you receive that?

**Comment by atztogo** [comment]
@site-g, I opened a WIP PR of #140. I will work there.

**Comment by site-g** [comment]
Ok, then I will close this PR.

**Comment by atztogo** [comment]
@site-g, you pushed your changes to your layer-group branch today. I get merge-conflict to merge those changes to the branch made for PR #140. So I will close PR #140 and open another PR to include your changes. Is it OK?

**Comment by site-g** [comment]
That's OK. I force pushed my commits after rebase the branch to the latest develop branch, which seems to have broken it.

**Pull request closed without merging**
