### PR TITLE
Fix: build wheel workflow

### PR DESCRIPTION
**Pull request by LecrisUT**
Either the emulation is needed in order to build for linux-arm or we can try CircleCI.

~~Experimenting with CircleCI for a while in https://github.com/LecrisUT/spglib/actions/workflows/ci.yaml~~

Will come back to CircleCI and CirrusCI in a later PR.

### CODE REVIEW

**Comment by LecrisUT** [comment]
@lan496 This one can be merged, but after merging, trigger a `CI` workflow manually with the default settings and `Upload wheel as an artifact`. If that one works, and you see al of the `x86_64`, `aarch64` wheels, it should be good to do another `rc`

[Here](https://github.com/LecrisUT/spglib/actions/runs/6103973236) is a run on my fork for reference if you want to wait for it before merging.

**Comment by lan496** [comment]
Artifacts do not seem to be uploaded https://github.com/spglib/spglib/actions/runs/6073266832?pr=321.
What happened the CI: `CI / build-wheel / Build source distribution`?

**Comment by LecrisUT** [comment]
There seems to be a bug with running `python3 -m  build` the symlink for `'spglib-2.1.0rc3/test/package/FetchContent/c/main.c'` points to `'spglib-2.1.0rc3/test/package/main.c'`, but `python3 -m build` is reporting to point to `/main.c`. That is a weird bug on upstream

Yes, it is a bug: https://github.com/python/cpython/pull/107846. Seems we have to wait for: https://github.com/python/cpython/issues/107845

**Comment by LecrisUT** [comment]
Can check the run [here](https://github.com/LecrisUT/spglib/actions/runs/6104366753), specifically check the artifacts have all wheels

**Comment by lan496** [comment]
It seems actions/upload-artifacts was skipped 🤔
https://github.com/LecrisUT/spglib/actions/runs/6104366753/job/16566506128
image

**Comment by LecrisUT** [comment]
Oh, right, I forgot to include the flag to upload [this one](https://github.com/LecrisUT/spglib/actions/runs/6109140599) should have it.

**Review by lan496 — APPROVED** [review]
Thanks! I've checked the artifact is uploaded.

**Pull request merged**
