### PR TITLE
Tighten magnetic tolerance for judging type-II MSG

### PR DESCRIPTION
**Pull request by lan496**
Fixes: https://github.com/spglib/spglib/issues/186

When magnetic moments `m` and `-m` are equal up to `mag_symprec`,
m - (-m) = 2m < mag_symprec should be satisfied. Thus, we need to judge
`m` as zero up to `0.5 * mag_symprec`.

### CODE REVIEW

**Comment by lan496** [comment]
@atztogo If no problem, I will merge this PR.
I am not sure how small a patch version should be, but this patch should be included in v.2.0.1.

**Comment by atztogo** [comment]
Please go ahead. About non-major version releases, we can release whenever we want. For the release we need to write a sentence at https://github.com/spglib/spglib/blob/develop/doc/releases.md for package maintainers.

**Comment by lan496** [comment]
@atztogo Thanks for the clarification. The title of this PR will be enough for the release note.
I will notify the corresponding pymatgen's issue when the next non-major version releases.

**Comment by atztogo** [comment]
Thanks!

**Pull request merged**
