### PR TITLE
Add fortran tests and clean cmake

### LINKED ISSUE #225: Fortran interface test using ctest
As pointed out at #224, we need fortran interface test, which seems reasonably done using ctest. I found [an instruction](https://qiita.com/implicit_none/items/dc83695c301f107dbd6c) though written in Japanese language.

### PR DESCRIPTION
**Pull request by LecrisUT**
@atztogo @lan496 

Here is the skeleton for the Fortran tests. Simply print to stdout/stderr and return non-zero for any failed test, and make sure the file name and function are identical.

I have also made a minor fix in the `find_package(Python)`, switching it to `Python3` for easier packaging in RPM (waiting on scikit-build/scikit-build#834 to finish that).

You should have write access to my branch, so feel free to just push commits on top of it.

Edit: Previous tests had some issues with sanitizer flags, which I had cleaned up in a separate branch, so I decided to just add these ones in as well. So all together this PR does:

- Adds a ctest skeleton for fortran tests
- Removes the separate targets for shared and static libraries. Instead use `spglib_SHARED_LIBS` to switch between either of those.
  - Reasoning: static libraries would only be useful if spglib is bundled in a project. Otherwise, for local development or production it should be using shared libraries
  - I've added a default value to static libraries if spglib is bundled, otherwise build shared (similar to `spglib_WITH_TESTS`)
- Adds namespaced alias targets and namespaced options
  - This is similarly to the one above, if the project is a bundled project, it should not be injected by the options of the parent project
  - This is still in `rc`, and there has been some previous changes to these flags, when I made this project importable, so it shouldn't affect much
- Use `FindPython3` for better compatibility with RPM packaging

Closes #225, #122

### CODE REVIEW

**Comment by LecrisUT** [comment]
Ok, since the last tests failed, I think I will just add the other fixes I had lying around. I'll edit the top comment for more details.

**Review by lan496 — APPROVED** [review]
@LecrisUT, many thanks! I see some configurations in `CMakeLists.txt` are moved to `src/CMakeLists.txt`.

@atztogo I am not a Fortran person. So, can you check and merge this PR?

**Comment by atztogo** [comment]
Merged. Thanks @LecrisUT. This is really great.
I just started to learn how to write tests in C (thanks @lan496 for the google test and @LecrisUT for ctest). It was good for me to know that fortran tests can also be handled by ctest.

**Comment by atztogo** [comment]
@LecrisUT, do you know the license of `c_interface_module.F90`? If it is from Fortran wiki or it is unclear, it is better not to use it. The license of full Fortran wiki is GPL, https://fortranwiki.org/fortran/show/Fortran+Wiki, though not sure for a part of it.

**Comment by atztogo** [comment]
@LecrisUT. Sorry, it seems public domain about source code on Fortran wiki, https://fortranwiki.org/fortran/show/Copyrights.

**Comment by LecrisUT** [comment]
Yeah, that's what I've found as well. As far as I understand there are no copyright or license restrictions with those.

**Pull request merged**
