### PR TITLE
Various fixes

### LINKED ISSUE #313: Fortran module install directory
I just encountered a fortran incompatibility when compiling with intel compiler when the original package is installed from gcc (the compiler simply refuses to run). Therefore the install dir of the Fortran module should be prefixed by the abi/fortran compiler. CMake does something similar for C++ modules. Fortran-stdlib uses a super safe [installation path](https://github.com/fortran-lang/stdlib/blob/7ff67627810a371cb81cb55aeb4aa42ce3708d3c/config/CMakeLists.txt#L3C1-L11), which can be used here as well

Related reference:
- https://gitlab.kitware.com/cmake/cmake/-/issues/19608
- https://discourse.cmake.org/t/api-design-c-modules-source-listings-and-interface-properties/5389/14

### PR DESCRIPTION
**Pull request by LecrisUT**
- Fix Fortran module install location
- Added examples to Fedora CI
- Added packaging tests to Fedora CI

Closes #313

### CODE REVIEW

**Comment by lan496** [comment]
Thanks! I will defer to atztogo on this PR.

**Comment by atztogo** [comment]
@LecrisUT, could you tell me what I can review? I have really no idea about rpm.

**Comment by LecrisUT** [comment]
Basically only a4190b73a568fee0cd09a46c68b66ffe4c2f8e95. On the fortran side it just changes the installation location from `/usr/include/spglib_f08.mod` to `/usr/include/spglib/gcc-13/spglib_f08.mod` so that you can install the `intel`, `flang` variants etc.

The additional tmt packaging simply runs a shell command, e.g.: https://github.com/spglib/spglib/pull/315/files#diff-9b6e070f697bf675cd4bc6193a4e168ca09b23dc1cd3b7ac0a0adeccb89f92b3R21-R24 and displays the output. I will update with a link of the example output. If you think it would be good to actually check the results of the output example, let me know, otherwise it's just a simple smoke test. The purpose for that additional test is to primarily check that the package is loaded correctly from cmake. I will alter it a bit later to check also `FetchContent` and `pkg-config`.

**Comment by atztogo** [comment]
@LecrisUT, thanks for your detailed explanation. All OK to me.

**Review by atztogo — APPROVED** [review]

**Comment by LecrisUT** [comment]
@atztogo @lan496 Check ` /distro/plans/examples` -> ` /example/c_api` [here](https://artifacts.dev.testing-farm.io/19d93d36-2bff-437b-8900-b5825691b12e/) for an example of the tmt test runner

**Comment by LecrisUT** [comment]
Waiting on: https://github.com/scikit-build/scikit-build-core/pull/468 after which will re-run the CI and then merge this.

/packit test

**Pull request merged**
