### PR TITLE
Fix typo in link to `spglib` paper

### PR DESCRIPTION
**Pull request by mkhorton**
Very minor PR, I just noticed a link was broken. Thank you for the great work (as always!) and the very exciting new magnetic symmetry features :)

### CODE REVIEW

**Comment by LecrisUT** [comment]
See #361

**Comment by mkhorton** [comment]
Ah I’d missed that, will close!

**Comment by LecrisUT** [comment]
No worries, thanks for the effort

**Comment by atztogo** [comment]
Thanks @mkhorton!

**Pull request closed without merging**
