### PR TITLE
Release v2.5.0

### LINKED ISSUE #486: Release v2.5.0
## TODO
- [x] https://github.com/spglib/spglib/pull/479
- [x] https://github.com/spglib/spglib/pull/485
- [x] https://github.com/spglib/spglib/pull/490
- [x] https://github.com/spglib/spglib/issues/407

@atztogo @LecrisUT Please update todos for the next minor release

### PR DESCRIPTION
**Pull request by lan496**
Closes https://github.com/spglib/spglib/issues/486

After this PR is merged, I'll put `v2.5.0` tag to the commit.

### CODE REVIEW

**Review by atztogo — APPROVED** [review]

**Review by LecrisUT — APPROVED** [review]

**Comment by lan496** [comment]
```shell
 1089  gco develop
 1090  git pull upstream develop
 1091  git log
 1092  git tag v2.5.0
 1093  git push upstream v2.5.0
```
https://github.com/spglib/spglib/actions/runs/9851199010

**Comment by lan496** [comment]
https://github.com/spglib/spglib/actions/runs/9851199010/job/27200153110

Failed to upload to PyPI
```
Uploading spglib-2.5.0-cp310-cp310-linux_aarch64.whl
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Binary wheel 'spglib-2.5.0-cp310-cp310-linux_aarch64.whl' has an       
         unsupported platform tag 'linux_aarch64'.   
```

@LecrisUT How to deal with it?

**Comment by LecrisUT** [comment]
I just saw that. I believe it's related to https://github.com/pypa/cibuildwheel/releases/tag/v2.19.2

> - 🐛 Update manylinux2014 pins to versions that support past-EoL CentOS 7 mirrors. (https://github.com/pypa/cibuildwheel/pull/1917)

Previous release had `manylinux_*` tag. Let's get [`renovate`](https://github.com/marketplace/renovate), we need to keep up with updates at least before a tag push. Can you install the app, I'll make a PR to configure it. Can check [this](https://github.com/LecrisUT/tmt-cmake/issues/10) and [this](https://github.com/LecrisUT/tmt-cmake/pull/13) to see it in action.

**Comment by lan496** [comment]
Thanks! I've installed under spglib org.

image

**Comment by LecrisUT** [comment]
Thanks, it is working now. But even after the update, the issue still persists, I've submitted an issue upstream, let's see how that turns out. This could even be a PyPI issue because, afaiu `manylinux` is based on centos 7 which was officially decommissioned at the beginning of the month.

**Pull request merged**
