### PR TITLE
Set C standard to C11

### PR DESCRIPTION
**Pull request by LecrisUT**
TODO:
- [x] Documentation

### CODE REVIEW

**Comment by atztogo** [comment]
@LecrisUT, are we waiting for windows test by #286?

**Comment by LecrisUT** [comment]
For this one? No it's self-contained and all ready. Just need documentation review.

**Comment by atztogo** [comment]
I asked because I have been bitten by windows compilers number of times in old days. So I may be relaxed if I could see this PR passes on windows compilers.

**Comment by LecrisUT** [comment]
> I asked because I have been bitten by windows compilers number of times in old days. So I may be relaxed if I could see this PR passes on windows compilers.

Oh in that sense. Sure this one is already a dependency for most of the PRs, #286 included. And indeed for that one the tests are passing (except the flakiness bug that I'm slowly trying to address with #303, #297 and other test improvements)

**Comment by LecrisUT** [comment]
Ok, see #286. Windows tests are passing with the C11 even on pytest :tada:. I have confirmed that the correct compiler is used in https://github.com/spglib/spglib/actions/runs/5319593736

**Review by atztogo — APPROVED** [review]

**Review by lan496 — APPROVED** [review]
LGTM! The newer standard will make our lives easier.

**Comment by LecrisUT** [comment]
Screenshot_20230620_135849
Hmm, it didn't allow to set an `auto-merge`, maybe it only has an effect on future PRs.

**Pull request merged**
