### PR TITLE
Use tag format for PyPi action

### PR DESCRIPTION
**Pull request by LecrisUT**
This is taken from #241

### CODE REVIEW

**Comment by lan496** [comment]
@LecrisUT Thanks. Can you update `Contributing.md`?

**Comment by LecrisUT** [comment]
Oh yeah, forgot about that

**Review by lan496 — APPROVED** [review]
@LecrisUT The instruction of `Contributing.md` looks nice! I've checked to run wheel-building CI in my forked repo.
https://github.com/lan496/spglib/actions/runs/4289284752

**Comment by LecrisUT** [comment]
@lan496 can you edit the pyproject.toml and push tag `v2.1.0-rc1`?

**Comment by lan496** [comment]
@LecrisUT Sure. Which branch is appropriate to push in this case?

**Comment by LecrisUT** [comment]
It is commit specific, but add a commit to edit pyproject.toml on develop and tag that commit.

**Comment by lan496** [comment]
@LecrisUT I've pushed https://github.com/spglib/spglib/commit/e78c3de1f5d36e2e6b2a69bacc600ff7e5c23388 to develop branch.

**Comment by LecrisUT** [comment]
Great, thanks. For some reason I am able to create releases, even though I can't push tags :))

**Comment by lan496** [comment]
Sorry, I didn't notice "write" role cannot push tags. I'll add you "Maintain" role.
https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by LecrisUT** [comment]
Thanks, didn't know the difference in the roles either.

**Pull request merged**
