### PR TITLE
Release v2.4.0

### LINKED ISSUE #434: Release v2.4.0
Let's release type check (merged in https://github.com/spglib/spglib/pull/420) because the recent drop of ase.Atoms seems to cause surprise to not a few users.

## TODO
- [x] https://github.com/spglib/spglib/pull/308
- [x] https://github.com/spglib/spglib/pull/435
- [x] https://github.com/spglib/spglib/pull/437
- [x] https://github.com/spglib/spglib/pull/457
- [x]  https://github.com/spglib/spglib/pull/431

@LecrisUT @atztogo Do you have any leftovers for the next minor version?

### PR DESCRIPTION
**Pull request by lan496**
Closes https://github.com/spglib/spglib/issues/434

After this PR is merged, I'll put `v2.4.0` tag to the commit.

### CODE REVIEW

**Review by LecrisUT — APPROVED** [review]
:+1: LGTM

One thing we might need to consider is the usage of PR links, it is a bit inconsistent right now. For the file, git blame can be used to find when an entry was added, but adding the links might be useful for the user to navigate those changes as well. On the other hand is the user using `ChangeLog.md` or the release pages?

I have found a neat GH action ([`changesets/action`](https://github.com/changesets/action)) that `mystmd` is [using](https://github.com/executablebooks/mystmd/pull/1088) which generates the Release PR after each commit. That would help keep things more consistent.

**Review by atztogo — APPROVED** [review]

**Comment by lan496** [comment]
```
gco -
git pull upstream develop
git tag v2.4.0
git push upstream v2.4.0
```

**Comment by LecrisUT** [comment]
BTW, we need to fix [this issue](https://github.com/scikit-build/scikit-build-core/issues/695) before the next release. I have made a bit of noise on Fedora and upstream `setuptools-scm` to get some ideas on how to handle this. Nothing we can do right now until we find a compatible solution

**Comment by lan496** [comment]
> One thing we might need to consider is the usage of PR links, it is a bit inconsistent right now.

I'm not sure what is inconsistent. Does it mean that the PR link itself does not indicate the commit where the change was included?

> On the other hand is the user using ChangeLog.md or the release pages?

I have no idea...

**Comment by LecrisUT** [comment]
> I'm not sure what is inconsistent. Does it mean that the PR link itself does not indicate the commit where the change was included?

Some entries have the PR link at the beginning of the entry, some do not. In the `Main Changes` section I do not believe it would be good to have, but for the other sections, it can go either way. For most cases I don't add them because there can be multiple changes that are documented in a PR.

**Pull request merged**
