### PR TITLE
Move type aliases outside TYPE_CHECKING and replace deprecated interface usage

### LINKED ISSUE #486: Release v2.5.0
## TODO
- [x] https://github.com/spglib/spglib/pull/479
- [x] https://github.com/spglib/spglib/pull/485
- [x] https://github.com/spglib/spglib/pull/490
- [x] https://github.com/spglib/spglib/issues/407

@atztogo @LecrisUT Please update todos for the next minor release

### PR DESCRIPTION
**Pull request by lan496**
Resolves https://github.com/spglib/spglib/issues/486#issuecomment-2210700032

### CODE REVIEW

**Comment by LecrisUT** [comment]
We can still keep the `if TYPE_CHECKING` part, we just need the alias definitions outside of it. Those the `|` operator not work on python 3.9?

Can you add `-Werror` to
https://github.com/spglib/spglib/blob/3486a6d59c5dc967ed6dc4fd13013e61525d8064/pyproject.toml#L115
We should also do something similar for the CMake builds and tests, the examples are using deprecated api as well.

**Comment by LecrisUT** [comment]
I didn't find ny more usage in `spglib.py`, but try to use the regex pattern [`\[['"]\w+["']\]`](https://regex101.com/r/vSzwBS/1). At least in example I've found usage

**Comment by lan496** [comment]
> Those the `|` operator not work on python 3.9?

No, python 3.9 complains "TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'"
https://github.com/spglib/spglib/actions/runs/9814689958/job/27102679055

**Comment by LecrisUT** [comment]
About the Fedora failures, update `.distro/Relax_numpy_requirements.patch` to:
```diff
Subject: [PATCH] Relax numpy requirements
---
Index: pyproject.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pyproject.toml b/pyproject.toml
--- a/pyproject.toml	(revision c4f576776c61725f90bd6becfb57b26a8c223883)
+++ b/pyproject.toml	(date 1720423830036)
@@ -1,7 +1,7 @@
 [build-system]
 # Numpy build and runtime dependencies are linked to ABI compatibility
 # A new wheel rebuild is needed when changing these
-requires = ["scikit-build-core", "numpy~=2.0"]
+requires = ["scikit-build-core", "numpy"]
 build-backend = "scikit_build_core.build"
 
 [project]
@@ -13,7 +13,7 @@
 readme = "python/README.rst"
 dynamic = ["version"]
 dependencies = [
-    "numpy>=1.20,<3",
+    "numpy>=1.20",
     "importlib-resources; python_version<'3.10'",
     "typing-extensions; python_version<'3.10'",
 ]
```

I still see issues with `example_full.py`. As a dirty fix, can you do the following patch:
```diff
--- a/test/example/CMakeLists.txt	(revision c4f576776c61725f90bd6becfb57b26a8c223883)
+++ b/test/example/CMakeLists.txt	(date 1720425410296)
@@ -20,10 +20,10 @@
 
 if (SPGLIB_WITH_Python)
     add_test(NAME example-python
-            COMMAND ${Python_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/python_api/example.py
+            COMMAND ${Python_EXECUTABLE} -Werror ${CMAKE_CURRENT_SOURCE_DIR}/python_api/example.py
     )
     add_test(NAME example-python-full
-            COMMAND ${Python_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/python_api/example_full.py
+            COMMAND ${Python_EXECUTABLE} -Werror ${CMAKE_CURRENT_SOURCE_DIR}/python_api/example_full.py
     )
     set_property(TEST example-python example-python-full
             APPEND PROPERTY
```

I will try to address them properly later together with the cmake tests.

**Review by LecrisUT — APPROVED** [review]
Ok, I've tested locally and `-Werror` worked, just that `get_symmetry` is not converted. I don't think that one should be converted to a dataclass in that form though.

**Comment by lan496** [comment]
> I will try to address them properly later together with the cmake tests.

Should I wait for your work before releasing the next version?

**Comment by LecrisUT** [comment]
> > I will try to address them properly later together with the cmake tests.
> 
> Should I wait for your work before releasing the next version?

No, go ahead. I'm waiting on #458 and #394, which should be merged after 2.5 release

**Pull request merged**
