### PR TITLE
feat: Switch to `importlib.resources`

### PR DESCRIPTION
**Pull request by LecrisUT**
In principle this should allow us to use `pip install -e .` and be able to debug more easily. But this requires upstream `scikit-build-core` to add an implementation:
- [x] https://github.com/scikit-build/scikit-build-core/pull/399

Depends on: #335

### CODE REVIEW

**Comment by LecrisUT** [comment]
~~This one is more-or-less ready. Just checking how codecov is reporting if we can simplify things~~

Scratch that it is still failing in pytest. Will investigate

**Comment by lan496** [comment]
~~Can you rebase develop?~~

OK, let's follow the order: #397 -> #335 -> #308
https://github.com/spglib/spglib/pull/335#issuecomment-1914248387

**Comment by LecrisUT** [comment]
Ok, I've added the comments for the changelog for this trio and all is ready for final review

**Comment by lan496** [comment]
@LecrisUT Can you resolve conflicts?

**Comment by LecrisUT** [comment]
Ok, resolved, I'll let you check one more time the changes.

**Review by lan496 — APPROVED** [review]

**Pull request merged**
