### PR TITLE
Change `SPGCONST` to `const`

### PR DESCRIPTION
**Pull request by LecrisUT**
I think this is no longer necessary

### CODE REVIEW

**Comment by atztogo** [comment]
`SPGCONST` implies `const`, but `const` emits warning. I made it easy-to-read the code. Do you have a better idea?

**Comment by LecrisUT** [comment]
Oh, it is supposed to be the other way around, I'll test to see what warning it throws

**Comment by atztogo** [comment]
It is something like "incompatible pointer type".

I'm sorry for badly written codes. Spglib code was maintained almost alone for long time, so it was enough if I understand it. But now I should explain more about details.

**Comment by LecrisUT** [comment]
Ok, this one is an issue:
`tmat` here is marked as `SPGCONST`:
https://github.com/spglib/spglib/blob/1d17e5e410d7ba6635c5e8529dd842e5a158bc53/src/magnetic_spacegroup.c#L257
But it call `mat_inverse_matrix_d3` which changes it:
https://github.com/spglib/spglib/blob/1d17e5e410d7ba6635c5e8529dd842e5a158bc53/src/magnetic_spacegroup.c#L452
https://github.com/spglib/spglib/blob/1d17e5e410d7ba6635c5e8529dd842e5a158bc53/src/mathfunc.c#L268

So it is indeed an implementation error that should be fixed. I.e. copy it if you want to edit it.

**Comment by LecrisUT** [comment]
https://github.com/spglib/spglib/blob/1d17e5e410d7ba6635c5e8529dd842e5a158bc53/src/mathfunc.c#L268-L289
You don't need to save to a temporary array `c` here. The intent of `m` is always to be overwritten, and you don't use it anywhere else.

I think most of these issues can be resolved, it just needs a bit of working through to detangle the intents. Some doxygen comments would help, even if it is internal. Just what are each argument meant to be.

Oh, you're allowing for operations on the same pointer like `mat_inverse_matrix_d3(a,a)`

**Comment by LecrisUT** [comment]
Note that there are a lot of redundant `func(const double variable)`. `variable` is always passed by value. `const` is only meant to be used for pointers and references to guarantee the function caller that it is not editted. When you pass by value, it is copies, so it becomes meaningless in that regard. Use `func(double variable)`. Use something like CLion to automatically detect and correct these issues.

Anyway, there were only 4 spots that needed fixing, excluding the thousands of meaningless `func(const double variable)`.

**Comment by atztogo** [comment]
> Note that there are a lot of redundant `func(const double variable)`. `variable` is always passed by value. `const` is only meant to be used for pointers and references to guarantee the function caller that it is not editted.

Indeed! I tend to use `const` to remember the variable not to be changed in the function. But you are correct. It should be fixed.

**Comment by atztogo** [comment]
> Oh, you're allowing for operations on the same pointer like `mat_inverse_matrix_d3(a,a)`

This can happen. So I think it is safe to write in this way, but I don't mean this is the best way.

**Comment by LecrisUT** [comment]
Indeed. To be honest I don't know of an elegant way to do it without C++ templates, and otherwise if the non-copy is worth it for a 3x3 matrix. I would do it on my codes just for the designing exercise

**Comment by LecrisUT** [comment]
Rminder: if we merge #257 I need to add some words there.

With regards to versioning, I don't think it is that severe since there was an indication of the intent, we just might have allowed people to shoot themselves in the foot. I don't think we need to increase a major just for this. As long as the bindings are correctly configured also

**Comment by LecrisUT** [comment]
We should merge this soon, the const is not enforced in the current state.

**Review by atztogo — APPROVED** [review]
Great. Thanks @LecrisUT!

**Pull request merged**
